"""add image_id to reports

Revision ID: 9bb8ba24522e
Revises: 
Create Date: 2025-07-19 14:40:37.560103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb8ba24522e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reports', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'image_id')
    op.drop_column('images', 'file_path')
    # ### end Alembic commands ###
